---
title: "Model"
author: "Elizabeth Guo"
date: "11/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fs)
library(gt)
library(tidymodels)
library(rsample)
library(readxl)
library(tidyverse)
```

```{r read in data and clean}
justicedem <- read_xlsx("Final_Project/justicesdata.xlsx")
justicevote <- read_csv("Final_Project/justicevote.csv",
                        col_types = cols(
                            justice = col_double(),
                            term = col_double(),
                            direction = col_double()
                        ))

justicedem %>% select(spaethid)

fullvotes <- justicevote %>% 
  inner_join(justicedem, by = c("justice" = "spaethid")) %>% 
  filter(!is.na(direction)) %>% 
  filter(yrnom >= 1948) %>% 
  mutate(votedirection = as.factor(ifelse(direction == 1, "Conservative", "Liberal"))) %>% 
  mutate(party = as.numeric(ifelse(parnom == 6, 0, 1)))

# Where Republican is 0, and Democrat is 1
```


```{r model 1 personal identity}
logistic_reg() %>%
  set_engine("glm") %>%
  fit(data = fullvotes, votedirection ~ nomrelig + famses + race + childsur) %>%
  predict(new_data = fullvotes) %>%
  bind_cols(fullvotes) %>%
  metrics(truth = votedirection, estimate = .pred_class) %>%
  gt() %>% 
    tab_header("Model 1 Evaluation on All Data")
```

```{r model 2 political affiliation}
logistic_reg() %>%
  set_engine("glm") %>%
  fit(data = fullvotes, votedirection ~ parnom) %>%
  predict(new_data = fullvotes) %>%
  bind_cols(fullvotes) %>%
  metrics(truth = votedirection, estimate = .pred_class) %>%
  gt() %>% 
    tab_header("Model 2 Evaluation on All Data")
```

```{r model 3 president appointed}
logistic_reg() %>%
  set_engine("glm") %>%
  fit(data = fullvotes, votedirection ~ prespart) %>%
  predict(new_data = fullvotes) %>%
  bind_cols(fullvotes) %>%
  metrics(truth = votedirection, estimate = .pred_class) %>%
  gt() %>% 
    tab_header("Model 3 Evaluation on All Data")
```




```{r}

glm_2 <- glm(formula = direction ~ party, data = fullvotes)


glm_2 %>% 
  ggplot(aes(x = party, y = direction)) +
  geom_jitter(height = 0.3, width = 0.2, alpha = 0.05) +
  geom_smooth(method = "glm", method_args = list(family = "binomial"), se = TRUE) +
  labs(title = "Relationship between Justice's Party and Vote Direction",
       subtitle = "Running a logistic regression",
       x = "Party of Justice at Nomination",
       y = "Direction of Vote",
       caption = "Party (0 = Republican, 1 = Democrat)
       Direction (1 = Conservative, 2 = Liberal)")
```

```{r}
fullvotes$issueArea <- as.factor(fullvotes$issueArea)

fullvotes$issueArea2 <- fullvotes$issueArea
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('1'), 'Criminal Procedure', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('2'), 'Civil Rights', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('3'), 'First Amendment', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('4'), 'Due Process', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('5'), 'Privacy', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('6'), 'Attorneys', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('7'), 'Unions', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('8'), 'Economic Activity', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('9'), 'Judicial Power', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('10'), 'Federalism', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('11'), 'Interstate Relations', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('12'), 'Federal Taxation', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('13'), 'Misc.', fullvotes$issueArea2)
fullvotes$issueArea2 <- ifelse(fullvotes$issueArea2 %in% c('14'), 'Private Action', fullvotes$issueArea2)

fullvotes %>% 
  filter(term == 2018) %>% 
  ggplot(aes(x = party, y = direction, color = issueArea2)) +
  geom_jitter(height = 0.3, width = 0.2, alpha = 0.5) +
  labs(title = "Relationship between Justice's Party and Vote Direction: 2018",
       subtitle = "Scatterplot, Colored by Issue",
       x = "Party of Justice at Nomination",
       y = "Direction of Vote",
       color = "Legal Issue",
       caption = "Party (0 = Republican, 1 = Democrat)
       Direction (1 = Conservative, 2 = Liberal)")
```





