---
title: "Project"
author: "Elizabeth Guo"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(janitor)
library(skimr)
library(fs)
library(purrr)
library(broom)
library(tidyverse)
```

```{r data downloading and cleaning}

justicesdata <- read_xlsx("raw-data/justicesdata.xlsx")

# For justices who actually made it onto the bench. I tried "distinct()" and got the same number of rows. So no justices are repeated.

justices <- justicesdata %>% 
  filter(success == 1) 


  
# 1946 - 2018
  
votesmodern <- read_xlsx("raw-data/SCDB_2019_01_justiceCentered_Citation3.xlsx")


alldata <- justicesdata %>% 
  inner_join(votesmodern, by = c("spaethid" = "justice"))


# 1791 - 1945
# votesold <- read_xlsx("raw-data/SCDB_Legacy_05_justiceCentered_Citation.xlsx")
# votes <- merge(votesold, votesmodern)


```

```{r}
justices %>% 
  filter(yrnom <= 1841) %>% 
  count(nomrelig) %>% 
            ggplot(aes(x = nomrelig, y = n)) +
            geom_col() +
            labs(title = ("Number of Justices of Each Religion Appointed Since this Decade"))
```
```{r}




```


